### ISSUE TITLE
板块设计

### ISSUE THREAD

**Issue by lilm** [ishipin/ishipin#11]
个人账户中的板块和主页上的板块重复。
【职位】、【发布职位】和【我发布的职位】重复；
【简历管理】和【我收到的简历】重复
![default](https://cloud.githubusercontent.com/assets/11382460/6549744/63abe934-c653-11e4-9375-f39a4dbd4b1d.png)

**Comment by yaozhy** [comment]
职位中有发布职位的功能，但考虑发布职位是用户使用频率较高的一种操作，所以单独在标题栏上增加了一个独立的菜单项。
对于菜单项和个人中心的菜单中的条目重复问题，主要考虑是：
1. 系统的菜单是在所有页面上出现，即使没有个人中心，顶部菜单项仍然可用。
2. 如果有个人中心，个人中心是和个人相关的所有操作，可能和顶部菜单重复。

所以我觉得这个应该不算是一个Bug
@huyl-bigoo ，你怎么看？
