### ISSUE TITLE
合成后的视频方向旋转了90度

### ISSUE THREAD

**Issue by chenjin3** [ishipin/ishipin#17]
合成前视频
http://www.ishipin.net.cn/upload/resume/93fb5c77-8ee2-4964-8f89-ffb9588ad81e/v1.mp4
合成后视频
http://www.ishipin.net.cn/upload/resume/93fb5c77-8ee2-4964-8f89-ffb9588ad81e/a.mp4

**Comment by dishi790529** [comment]
增加一个提交参数&client=ios

**Comment by chenjin3** [comment]
已增加
