### ISSUE TITLE
用户注册没有输入邮箱这一项

### ISSUE THREAD

**Issue by lilm** [ishipin/ishipin#18]
用户注册没有输入邮箱这一项，但是注册步骤里有“邮箱激活”这个步骤。

**Comment by yaozhy** [comment]
Fixed on Mar 11 version, please help to re-verify the bug after this version published.

**Comment by lilm** [comment]
还是没有邮箱这一项。
增加的问题：注册页面，点击【提交】，跳转至登录页面。

**Comment by lilm** [comment]
邮箱没有问题了，但增加的问题：注册页面，点击【提交】，跳转至登录页面。仍存在

**Comment by yaozhy** [comment]
请访问我的电脑帮忙验证是否已经修正！
