### ISSUE TITLE
用户注册问题集锦

### ISSUE THREAD

**Issue by lilm** [ishipin/ishipin#2]
1.输入信息没有区分必填和选填；
2.输入昵称不会提示是否已存在；
3.密码没有长度提示和限制；
4.即使不输入任何信息，点击提交，都显示保存成功；
5.头像文件，选择文件无大小限制，也没有尺寸提示，选择后没有上传选项，或者预览界面，不知道是否上传成功；
6.出生日期没法输入；
7.点击【注册步骤】下面的几个按钮：【输入信息】、【信息审核】、【邮箱激活】、【注册成功】页面没反应；
8.在此页面上点击【用户注册】按钮，跳转至发布新职位页面。

![default](https://cloud.githubusercontent.com/assets/11382460/6549138/fd450e96-c648-11e4-9091-f85c68957578.png)
![2](https://cloud.githubusercontent.com/assets/11382460/6549139/fd6b85b2-c648-11e4-9077-39d777adbecb.png)

**Comment by yaozhy** [comment]
出去第五个问题：
5.头像文件，选择文件无大小限制，也没有尺寸提示，选择后没有上传选项，或者预览界面，不知道是否上传成功；
其他的应该已经修正了，请帮忙访问我的机器验证！

**Comment by lilm** [comment]
7.点击【注册步骤】下面的几个按钮：【输入信息】、【信息审核】、【邮箱激活】、【注册成功】页面没反应；
这个问题还在
