### ISSUE TITLE
首页最下方公司信息 格式问题

### ISSUE THREAD

**Issue by lilm** [ishipin/ishipin#22]
首页最下方公司地址等信息 格式没对齐 分行有问题

![311- 1](https://cloud.githubusercontent.com/assets/11382460/6589133/4faac0a2-c7d6-11e4-8c71-bef11f1f1de2.png)

**Comment by yaozhy** [comment]
请访问：http://192.168.0.131:8080/www/index.jsp

**Comment by yaozhy** [comment]
应该已经Fix了
