### ISSUE TITLE
信息填写部分

### ISSUE THREAD

**Issue by lilm** [ishipin/ishipin#46]
个人信息、公司信息填写部分，有三个图显示不出来：
![1](https://cloud.githubusercontent.com/assets/11382460/6613804/dbd96000-c8cc-11e4-82a3-a73f33f67611.png)
![2](https://cloud.githubusercontent.com/assets/11382460/6613805/dbdcdc76-c8cc-11e4-9acf-4e9333e5cf72.png)
![3](https://cloud.githubusercontent.com/assets/11382460/6613806/dbe2ab60-c8cc-11e4-9ac8-8075ffb5206c.png)

**Comment by yaozhy** [comment]
这个公司已经录入过资料单现在找不到了？
请重新注册一个账号试试。

**Comment by lilm** [comment]
上传图片后 这个图裂的图像就会变成上传的图片。但上传前还是图裂小图像。
