### ISSUE TITLE
简历

### ISSUE THREAD

**Issue by lilm** [ishipin/ishipin#9]
点击邸石简历，跳转至豆瓣页面。
![1](https://cloud.githubusercontent.com/assets/11382460/6549705/7c30403c-c652-11e4-9e1f-fd84b62d1130.png)
![2](https://cloud.githubusercontent.com/assets/11382460/6549706/7c87d540-c652-11e4-936a-51b52ffc1142.png)

**Comment by yaozhy** [comment]
与3月11日版本中已经修正，请帮忙确认！

**Comment by lilm** [comment]
这个bug没有变化
